version: "3.8"
services:
  auth:
    build: ./auth-microservice
    stdin_open: true
    tty: true
    container_name: auth
    env_file:
      - ./.env
    volumes:
      - ./auth-microservice:/opt/app
    networks:
      - btd-local
    ports: 
      - 3001:3000
networks:
  btd-local:
    external: true
